{% set name = "django-celery-results" %}
{% set url_name = "django_celery_results" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ url_name[0] }}/{{ url_name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: b5abe0c03c91dc8fe657e0c2a34c9604175838af13cb8c7f64654b3ad27febcf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - celery >=4.4,<5.0
    - python
    - django

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/celery/django-celery-results
  summary: Celery result backends for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
