{% set name = "django-celery-results" %}
{% set url_name = "django_celery_results" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ url_name[0] }}/{{ url_name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: 75aa51970db5691cbf242c6a0ff50c8cdf419e265cd0e9b772335d06436c4b99

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - celery >=5.2.3,<6.0
    - python >=3.6
    - django >=3.2.18,<4.1

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/celery/django-celery-results
  summary: Celery result backends for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
    - hadim
